import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const newake = localFont({
  src: "./fonts/Newake-Font-Demo.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${newake.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
