import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const newake = localFont({
  src: "./fonts/Newake-Font-Demo.otf",
  variable: "--font-newake",
});

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${newake.variable} ${geist.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-orange-50 flex flex-col font-geist">
        {children}
      </body>
    </html>
  );
}
